---
name: CLI-Release

on:
    workflow_dispatch:

defaults:
    run:
        shell: bash

permissions:
    contents: write

jobs:

    create-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Fetch all tags
              run: |
                  git fetch --force --tags

            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.20

            - name: Run GoReleaser
              uses: goreleaser/goreleaser-action@v2
              with:
                  distribution: goreleaser
                  version: ${{ env.GITHUB_REF_NAME }}
                  args: release --rm-dist
#                  workdir: ./app/cli
              env:
                  GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
